name: Docker

on:
  push:
    branches:
      - main

  # Run every day at 1 AM
  schedule:
    - cron:  '* 1 * * *'

env:
  IMAGE_NAME: counterstrikesource-base
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "$CR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          sha256sum Dockerfile > dockerfile.ver
          docker inspect --format='{{.Created}}' ubuntu:focal > ubuntu-focal.ver
          docker run --entrypoint=/bin/dpkg $IMAGE_NAME -l > packages.ver
          docker run --entrypoint=/bin/bash $IMAGE_NAME -c "find /opt/game -type f -print0 | sort -z | xargs -r0 sha256sum" > cstrike.ver

          cp -r deps deps_tmp
          if cmp -s dockerfile.ver deps/dockerfile.ver \
             && cmp -s ubuntu-focal.ver deps/ubuntu-focal.ver \
             && cmp -s packages.ver deps/packages.ver \
             && cmp -s cstrike.ver deps/cstrike.ver ; \
          then exit ; \
          fi

          mkdir -p deps_tmp
          mv -f dockerfile.ver deps_tmp/dockerfile.ver
          mv -f ubuntu-focal.ver deps_tmp/ubuntu-focal.ver
          mv -f packages.ver deps_tmp/packages.ver
          mv -f cstrike.ver deps_tmp/cstrike.ver

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Update dependency versions
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: deps_tmp
          TARGET_FOLDER: deps
